### ISSUE TITLE
Taxonomy: menu position not working if language is not English

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/menu_position#15]
If you are using another language than English the module doesn't create links.

DB log:

> Notice: Undefined property: Node::$language in menu_position_menu_position_condition_taxonomy() (line 42 of /mypath/modules/menu_position/plugins/menu_position.taxonomy.inc).

**Comment by laryn** [comment]
Thanks @djzwerg -- which version are you testing with?

**Comment by djzwerg** [comment]
I've downloaded the version from backdropcms.org (1.x-1.0.3 - the latest release from here, too). If I use the latest code from here the log notice changes to:

> Notice: Undefined property: Node::$language in menu_position_menu_position_condition_taxonomy() (line 41 of /mypath/modules/menu_position/plugins/menu_position.taxonomy.inc).

**Comment by laryn** [comment]
@djzwerg Are you able to test the PR in this link? I'm in the middle of working on that one and tried to make a few tweaks that should help with language. https://github.com/backdrop-contrib/menu_position/pull/14

In case it is helpful you can get all those changes in a zipped package here: https://github.com/laryn/menu_position/archive/refs/heads/1.x-1.x-issue12.zip

**Comment by djzwerg** [comment]
@laryn thanks! The error notice has been gone but the menu position role seems not to work. Steps to reproduce:

1. Change your side-wide language from English to another, e.g. German
2. Create menu link e.g. main menu -> test
3. Create taxonomy vocabulary and at least one term
4. Create content type and add taxonomy reference to your vocabulary
5. Add menu position: your content type and taxonomy term from no. 3 to your menu link from no. 2
6. Add a block (main menu, hierarchical tree, starting with level 2 and a depth of 1 or more)
7. Add some content
8. Look if you can see the block

In my case there is no block this way 😞

**Comment by djzwerg** [comment]
After a few more tests it looks like this issue is a general one (occurs not only to nodes with taxonomy references). If you want to use the core main menu block starting at level 2+ in combination with menu_position nothing is shown up. On D7 that way worked 🤔

**Comment by djzwerg** [comment]
@laryn should I open a new issue because of this?

**Comment by laryn** [comment]
@djzwerg If you are testing the branch above and it works in other configurations, yes, let's split this one out. I'd like to merge the big one that pulls in a bunch of old Drupal 7 commits and then have a place to start from for other issues.

**Comment by djzwerg** [comment]
@laryn I made a new one: https://github.com/backdrop-contrib/menu_position/issues/16

The error notice has been gone using this branch: https://github.com/laryn/menu_position/archive/refs/heads/1.x-1.x-issue12.zip. So I think this issue could be closed after applying the PR.

**Comment by laryn** [comment]
I just merged and did a quick test and a basic rule is working on a language other than English, so I'm closing this for now. I'll try to look at the other issue you created before making a release.
