### ISSUE TITLE
Core menu block is hidden when starting at level 2+ in combination with menu_position

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/menu_position#16]
Steps to reproduce:

1. Create menu link e.g. main menu -> test
2. Create content type
3. Add menu position: your content type to your menu link from no. 1
4. Add a block (main menu, hierarchical tree, starting with level 2 and a depth of 1 or more)
5. Add some content
6. Look if you can see the block

For now you don't see a menu block. If you change the starting level to 1 you will see the whole menu including the item of your viewed node.

**Comment by djzwerg** [comment]
As you describe yourself [here](https://github.com/backdrop-contrib/menu_position/issues/11) @laryn this workaround makes the hidden menu block showing (tested on Vanilla BD). So it looks like this issue is a duplicate of #11 but applying the branch from https://github.com/laryn/menu_position/archive/refs/heads/1.x-1.x-issue12.zip does not solve it.

**Comment by laryn** [comment]
Hi @djzwerg I am having trouble replicating this on the latest dev version here after merging in the commits from issue 12.

**Comment by djzwerg** [comment]
Hi @laryn let me try this on a vanilla installation

**Comment by djzwerg** [comment]
@laryn I can confirm that after merging the commits from #12 the bug has been fixed. Thanks a lot!
