### ISSUE TITLE
Issues on upgrade from Drupal 7

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/menu_position#5]
I have a site with relatively few Menu Position settings, and they seem to upgrade okay as far as the UI shows but they don't seem to work in the use case of a Menu Block. If I delete them and recreate the Menu Position settings in Backdrop, they look the same in the UI at a glance, but they work when used with Menu Blocks.

FYI for anyone else (with the workaround noted above). If I am able to figure this out in the scope of this site project I'll submit a PR, but if not the above should at least be helpful to others wondering why the rules don't seem to be working on an upgraded site...

**Comment by laryn** [comment]
Interestingly, I disabled the module and then reenabled it, and I saw this message:

> Existing menu position rules were discovered and have now been re-configured so they will continue to work. 

Now the menu blocks work as expected.

**Comment by laryn** [comment]
@jdanthinne Maybe it would make sense to call `menu_position_enable()` from inside an update hook to make sure that rules are all fixed on Drupal 7 upgrades? Unless you think it may have been something unique to the site I'm working on, which is maybe possible...

**Comment by jdanthinne** [comment]
@laryn Sorry I don't do Drupal/Backdrop anymore (switched to mobile dev 5 years ago). Feel free to update this module as you wish.
