### ISSUE TITLE
Change maintainer

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/menu_position#8]
@jdanthinne per [your comment here](https://github.com/backdrop-contrib/menu_position/issues/5#issuecomment-1351906343), I'll submit a PR to take over maintainership.

**Comment by laryn** [comment]
@jdanthinne PR submitted here: https://github.com/backdrop-contrib/menu_position/pull/9 

Are you able to still merge that, permissions-wise?

Thanks for your work over the years!

**Comment by jdanthinne** [comment]
Unfortunately, I don’t have write permission anymore.

**Comment by laryn** [comment]
No problem, I'll get it taken care of. Thanks again!

**Comment by klonos** [comment]
@laryn all done:

![image](https://user-images.githubusercontent.com/2423362/207705889-a8d43fa5-69a9-44c6-a623-eea2c2c03220.png)
